# fly.toml app configuration file generated for crawler-ai on 2025-07-16T00:16:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crawler-ai'
primary_region = 'sin'

[build]

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/stats'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
